baseURL = "https://kachanimbu.com/"
languageCode = "en-us"
title = "Kachanimbu"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "Vimal"
  description = "Average is awesome."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowRssButtonInSectionTermList = false
  ShowFullTextinRSS = true

[params.profileMode]
  enabled = true
  title = "Kachanimbu"
  subtitle = "Average is awesome."
  imageUrl = "/Profile.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Vimal"

[params.homeInfoParams]
  Title = "Kachanimbu"
  Content = "Average is awesome."

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3

[markup.highlight]
  noClasses = false
