baseURL = "https://kachanimbu.com/"
languageCode = "en-us"
title = "Kachanimbu"
theme = "PaperMod"
paginate = 10

[params]
  author = "Vimal"
  description = "Average is awesome."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false

[params.homeInfoParams]
  Title = "Kachanimbu"
  Content = "Average is awesome."

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup.highlight]
  noClasses = false
